#! /bin/sh

### BEGIN INIT INFO
# Provides:          home-temperature-take-samples
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: home-temperature-take-samples
# Description:       Takes temperature samples in background
### END INIT INFO


case "$1" in
  start)
    echo "Starting take samples process for home-temperature"
    cd /home/pi/workspaces/home-temperature
    ./take_samples.sh > /var/log/home-temperature-take-samples.log 2>&1 &
    ;;
  stop)
    echo "Stopping django server for home-temperature"
    pkill -f take_samples
    ;;
  *)
    echo "Usage: /etc/init.d/home-temperature-take-samples {start|stop}"
    exit 1
    ;;
esac

exit 0
